import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/layout/Header";
import Footer from "@/components/shared/layout/Footer";
import { Toaster } from "@/components/ui/sonner";
import { Fragment } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Fragment>
      <Header />
      {children}
      <Toaster position="top-center" richColors />
      <Footer />
    </Fragment>
  );
}
