import type { Metadata } from "next";
import { ThemeProvider } from "@/components/shared/darkmode/theme-provider";
import { Toaster } from "@/components/ui/sonner";

import QueryProvider from "@/providers/query-provider";
import localFont from "next/font/local";

import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const alibaba = localFont({
  src: [
    {
      path: "../../public/font/alibaba-bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/font/alibaba-regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${alibaba.className}`}>
        <QueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {children}
            <Toaster position="top-center" richColors />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
