import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/layout/Header";
import Footer from "@/components/shared/layout/Footer";
import { ThemeProvider } from "@/components/shared/theme/theme-provider";
import QueryProvider from "@/lib/api/QueryProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <QueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Header />
            {children}
            <Toaster position="top-center" richColors />
            <Footer />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
